# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char

  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies: ['mdformat-toc==0.5.0']

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.21.1"
    hooks:
      - id: pyproject-fmt
        args: ["--keep-full-version"]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.7
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.11
    hooks:
      # Run the linter
      - id: ruff-check
        args: [--fix, --show-fixes]
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-jinja
        files: src/pyvista_wasm/templates/.*\.html$
        args: ["--format-js", "--indent-js", "2"]
      - id: djlint-jinja
        files: src/pyvista_wasm/templates/.*\.html$

  - repo: https://github.com/biomejs/pre-commit
    rev: v2.4.12
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@2.4.10"]

  - repo: https://github.com/scientific-python/cookie
    rev: 2026.04.04
    hooks:
      - id: sp-repo-review
        additional_dependencies: ["repo-review[cli]"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.1
    hooks:
      - id: mypy
        files: ^src/.*\.py$
        # SPEC 0: Use minimum supported numpy version
        additional_dependencies: [numpy>=2.0]

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.20.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==24.10.0]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell

  - repo: https://github.com/tkoyama010/standard-readme-pre-commit
    rev: 06556851a2b176081b1e9af76392f6326201a7c8
    hooks:
      - id: standard-readme

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.24.1
    hooks:
      - id: zizmor

ci:
  autofix_commit_msg: |
    chore: auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'
  autoupdate_schedule: weekly
  submodules: false
