blank_issues_enabled: true
contact_links:
  - name: Security Vulnerabilities
    url: https://github.com/tkoyama010/pyvista-wasm/security/advisories/new
    about: Report security vulnerabilities privately
