name: API Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
        with:
          python-version: '3.12'

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          enable-cache: false

      - name: Install dependencies
        run: uv pip install --system pyvista ".[dev]"

      - name: Report API coverage
        run: pyvista-wasm api-coverage
